### ISSUE TITLE
help

### ISSUE THREAD

**Issue by freshstarfruit** [michal4132/szpoter#1]
music no play just farts

**Comment by michal4132** [comment]
pleese update kernel driver

**Comment by freshstarfruit** [comment]
i updated kernal and no screen picture nothing works now help

**Comment by michal4132** [comment]
fixed on master, now farts louder

**Comment by freshstarfruit** [comment]
cant pull master i have no screen and no see anything

**Comment by michal4132** [comment]
It's a feature. Confirmed headless mode works.
Can be closed
